apiVersion: apps/v1
kind: Deployment
metadata:
  name: apidemo
  labels:
    app: apidemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apidemo
  template:
    metadata:
      labels:
        app: apidemo
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: apidemo
          image: 10.0.0.41/apidemo/apidemo
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: apidemo
spec:
  selector:
    app: apidemo
  ports:
    - port: 80
      targetPort: 5000

